### ISSUE TITLE
html map is not saved if temporary_files dir does not exist

### ISSUE THREAD

**Issue by seepoww** [pali08/zanikle_obce_cz#1]
**Version:**
* master 1aac6cd35f846475a071169f75de4d156c3f055f

**Steps to reproduce:**
Assuming you have specified the town name or coordinates, and radius.

1.  Click on "by town"/"by coordinates"

**Current results:**
* App crashes followed by this stacktrace
```
Traceback (most recent call last):
  File "/Users/mdren/git/zanikle_obce_cz/gui_playground.py", line 138, in on_click_draw_by_town
    places = get_html_map_with_markers_town(self.ui.lineEdit_town.text(), self.html_map_filepath)
  File "/Users/mdren/git/zanikle_obce_cz/circle_area_webpage.py", line 43, in get_html_map_with_markers_town
    add_places_to_map(m, filepath, places)
  File "/Users/mdren/git/zanikle_obce_cz/circle_area_webpage.py", line 15, in add_places_to_map
    map.save(filepath)
  File "/Users/mdren/git/zanikle_obce_cz/venv/lib/python3.6/site-packages/branca/element.py", line 162, in save
    fid = open(outfile, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'temporary_files/map.html'
```

**Expected results**
* If `temporary_files/` directory does not exist, create it and save the temporary map in there.

**Comment by pali08** [comment]
Folder was added to git repository with .gitignore flag - So it will exist by default and also we will be sure, that map.html, that changes each search will not be versioned.
